### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [MuckRock/documentcloud-whisper-addon#7]
HELLO MAN...CONGRATULATIONS FOR YOUR AMAZING PROJECT!!!BUT COULD YOU PLEASE TELL ME STEP BY STEP WHAT I HAVE TO DO FOR USE YOUR AMAZING PROJECT?I AM NEW ON THIS AND I DONT KNOW!!!

**Comment by duckduckgrayduck** [comment]
Hi, this repository contains the code for a DocumentCloud Add-On. You run the program from within Documentcloud.org. DocumentCloud is a platform used by journalists and researchers all over the world. To use the Add-On, you have to have a DocumentCloud account and be verified. If you are not a journalist or researcher, is unlikely you can use this program. There are some standalone command line tools that run Whisper, the transcription library that this Add-On depends on, that you can use here: https://github.com/Purfview/whisper-standalone-win
